services:
  - type: web
    name: calendar-slots-app
    runtime: docker
    plan: free
    region: frankfurt
    branch: main
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      # Строка подключения Neon (Postgres) приходит из Environment Group «DB»
      - fromGroup: DB
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000